name: Build and Run Action

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker Image
      run: |
        docker build -t my-action .
    
    - name: Run Action
      run: |
        docker run -e INPUT_WHO-TO-GREET="Mona the Octocat" my-action

    - name: Commit Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Build and run action"
        git push
